version: 2
jobs:
  build:
    docker:
      - image: python:3.6
        environment:
          FLASK_ENV: testingci
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: bin/test.sh
